#!/bin/bash

# Start a job and return its pid.
# It need a param -- the job command name.
# eg: start /bin/sh test.sh
function start {
    local CLI=$@
    PID=`pgrep -f "$CLI"`

    if [ -z "$PID" ]
    then
        nohup $CLI > /dev/null &
    fi

    echo $PID
}

# Stop a job
# It need a param -- the job command name.
# eg: stop /bin/sh test.sh
function stop {
    local CLI=$@
    PID=`pgrep -f "$CLI"`

    if [ -n "$PID" ]
    then
        kill -9 $PID
    fi

}

# Restart a job
# It need a param -- the job command name.
# eg: restart /bin/sh test.sh
function restart {
    local CLI=$@
    stop $CLI
    start $CLI
}

# Print help information
function help {
    case $1 in
    "1")
        echo "You can do actions below: start | stop | restart";;
    "2")
        echo "You must give me the file path which including the jobs list.";;
    *)
        echo "Ooooops!";;
    esac
    exit
}

# Do action with all command
# param 1 -- action.eg:start, stop, restart
# param 2 -- job list path.
# eg: run start ./job.txt
function run {
    cat $2|while read line;do
        $1 $line
    done   
}

# check the first param.
if [ -z $1 ]
then
    help 1
fi

IS_AVAILABLE=0
for ACTION in start stop restart
do
    if [ $ACTION = $1 ]
    then
        IS_AVAILABLE=1
        break
    fi
done

if [ $IS_AVAILABLE == 0 ]
then
    help 1
fi

# check the second param
if [ -z $2 ]
then
    help 2
fi

if [ -r $2 ] && [ -f $2 ]
then
    echo 'running'
else
    help 2
fi

run $1 $2
