#!/bin/bash
#
# eg 1: nohup dkeeper start ./jobs.txt > /dev/null &
# eg 2: dkeeper stop ./jobs.txt

function start {
    local CLI=$@
    PID=`pgrep -f "$CLI"`

    if [ -z "$PID" ]
    then
        nohup $CLI > /dev/null &
        PID=`pgrep -f "$CLI"`
    fi

    echo $PID
}

function stop {
    local CLI=$@
    PID=`pgrep -f "$CLI"`

    if [ -n "$PID" ]
    then
        kill -9 $PID
    fi

}

function restart {
    local CLI=$@
    stop $CLI
    start $CLI
}

function help {
    case $1 in
    "1")
        echo "You can do actions below: start | stop | restart";;
    "2")
        echo "You must give me the file path which including the jobs list.";;
    *)
        echo "Ooooops!";;
    esac
    exit
}

function run {
    cat $2|while read line;do
        $1 $line
    done   
}

# check the action.
if [ -z $1 ]
then
    help 1
fi

IS_AVAILABLE=0
for ACTION in start stop restart
do
    if [ $ACTION = $1 ]
    then
        IS_AVAILABLE=1
        break
    fi
done

if [ $IS_AVAILABLE == 0 ]
then
    help 1
fi

# check the job list file path.
if [ -z $2 ]
then
    help 2
fi

if [ -r $2 ] && [ -f $2 ]
then
    echo 'running'
else
    help 2
fi

# OK, Let's go!
if [ $1 = "start" ]
then
    while true
    do
        run $1 $2
    done
fi

run $1 $2

# end of this script
