#!/bin/bash
#
# eg 1: nohup dkeeper start ./jobs.txt > /dev/null &
# eg 2: dkeeper stop ./jobs.txt

function start {
    local CLI=$@
    PID=`pgrep -f "$CLI"`

    if [ -z "$PID" ]
    then
        nohup $CLI > /dev/null &
        PID=`pgrep -f "$CLI"`
    fi

    echo $PID
}

function stop {
    local CLI=$@
    PID=`pgrep -f "$CLI"`

    if [ -n "$PID" ]
    then
        kill -9 $PID
    fi

}

function restart {
    local CLI=$@
    stop $CLI
    start $CLI
}

function help {
    case $1 in
    "1")
        echo "You can do actions below: start | stop | restart";;
    "2")
        echo "You must give me the file path which including the jobs list.";;
    "3")
        echo "Option -s is required.";;
    "4")
        echo "Option -f is required.";;
    *)
        echo "Ooooops!";;
    esac
    exit
}

function run {
    cat $2|while read line;do
        $1 $line
    done   
}

while getopts :s:f:v p
do
    case $p in
    s)
        # check the action.
        if [ -z $OPTARG ]
        then
            help 1
        fi

        IS_AVAILABLE=0
        for ACTION in start stop restart
        do
            if [ $ACTION = $OPTARG ]
            then
                IS_AVAILABLE=1
                break
            fi
        done

        if [ $IS_AVAILABLE == 0 ]
        then
            help 1
        fi

        OPTION_ACT=$OPTARG;;
    f)
        # check the job list file path.
        if [ -z $OPTARG ]
        then
            help 2
        fi

        if [ -r $OPTARG ] && [ -f $OPTARG ]
        then
            echo 'running'
        else
            help 2
        fi

        OPTION_FILE=$OPTARG;;
    v)
        echo "Deamon Keeper. version: 1.0"
        exit 0;;
    esac
done

if [ -z "$OPTION_ACT" ]
then
    help 3
fi

if [ -z "$OPTION_FILE" ]
then
    help 4
fi

# OK, Let's go!
if [ $OPTION_ACT = "start" ]
then
    while true
    do
        run $OPTION_ACT $OPTION_FILE
    done
fi

run $OPTION_ACT $OPTION_FILE

# end of this script
